server:
  port: 8080
  tomcat:
    remoteip:
      remote-ip-header: X-Forwarded-For
      protocol-header: X-Forwarded-Proto

spring:
  security:
    user:
      name: admin
      password: admin

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  admin:
    email: superadmin@superadmin.bilkent.edu
    password: admin

  datasource:
    url: 123
    username: 123
    password: 123
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      platform: postgres
      mode: always

  data:
    s3:
      accesskey: ak
      secretkey: sk
      region: rg

  jwt:
    secret: "asasas"
    ttl: 600000
    issuer: ticket-app

frontend:
  url: http://localhost:3000

springdoc:
  user:
    name: admin
    password: admin
  swagger-ui:
    path: /documentation
  api-docs:
    path: /documentation
